### ISSUE TITLE
new_value (-...) is smaller than 0!

### ISSUE THREAD

**Issue by tchncs** [tenplus1/hudbars#1]
Hi, i just tryed your (forked) mod and got the following issues...fequently by multible players in the log :/
```
ERROR[Server]: [hudbars] Bad call to hb.change_hudbar, 
identifier: “armor”, player name: “eiswind”. new_value (-36) is smaller than 0!
```

Edit: looks like a little damage solves this issue temporally
...sometime re-wearing armor

**Comment by tenplus1** [comment]
The mod belongs to wuzzy, the version I have on my github page is a highly edited version for Xanadu server.
